language: julia
os:
- linux
julia:
- 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_script:
- julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'
script:
- julia build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: SErzWuLgJ1oRQGzHik9lwny/1+VzgCHRCbnJPIItV7MY/CICnai+qEPb0fqYTXRVdCxADaHTPM9Pegg1OnNeVbwiWWphREfOt/T/0JdQeV97FdcLy7J5gfpZ+W9wTtBLPS+qjOVRvNOO13Ov5LPcGIEtdlHzVfTublXr73MGci1pvLitZmMSIb+fcciCqBVYN1BlNj80LvRMbec5TdUB1FfyUUkBT4Y3WvjSfQWCfAmc1/XB2X/8b5ym3eeWlVMtSwc2xS5FiB6YM7terTW+gzkAIXDcq7BPuy10XdC8ELByw+CXzHmXn8yzxHsm2xBnSRn+NuMxwPpTuLI0c79qOZU/wDSbXmkCUJUqE+87wzMh0FdepWo+heG5mdlTaevTC6GZ2KSVwzshQF9TV1eHzZUzGOWFeeSusmCymstLm2zUZgeHttDhPXkChJKG66L5F/xWxqBYplztOY1yeazeVU9i8GDvVhT7aNuun7CQSKmIHhUBIfG4q86TCKQFEIA/CTont6Dr5VLCD9GvIKAwx+hB7nblYFCtBfl4DN6BwIts78v3TBiZbErExOXfjX6hrzzyXzYi4fWnGAP3c9V/L/4IsNFoZ9rKaui5lqo/Bqbje8z3pGhZjcpPtWvPWsBscOlFXz3s1JMD05elLeq+oBLjtzc4C9TE8iIxUTn5qCg=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: isuruf/MPCBuilder
    tags: true
